name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - closed

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install buf CLI
        uses: bufbuild/buf-setup-action@v1

      - name: Generate Swagger JSON
        run: |
          buf generate --template buf.gen.doc.yaml

      - name: Install swagger-cli
        run: npm install -g swagger-cli

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: docs/api/v1/*

      - name: Upload Documents
        uses: actions/upload-pages-artifact@v3
        with:
          # 絶対パスを指定
          path: swagger-ui

      # - name: Install swagger-cli
      #   run: |
      #     npm install -g swagger-cli

      # - name: Validate Swagger Files
      #   run: |
      #     swagger-cli validate -d openapi.yaml --type yaml

      # - name: Generate Swagger UI
      #   uses: Legion2/swagger-ui-action@v1
      #   with:
      #     output: swagger-ui
      #     spec-file: openapi.yaml

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: swagger-ui
