name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - closed

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install buf CLI
        uses: bufbuild/buf-setup-action@v1

      - name: Generate Swagger JSON
        run: |
          buf generate --template buf.gen.doc.yaml

      - name: Checkout swagger-ui
        uses: actions/checkout@v3
        with:
          repository: swagger-api/swagger-ui
          ref: 'v4.15.0'
          path: swagger-ui

      - name: Inject Swagger static files
        run: cp -n swagger-ui/dist/* docs

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: docs/hello.swagger.json
          github_token: ${{ secrets.GITHUB_TOKEN }}


      - name: Push gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
