name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - closed

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install buf CLI
        uses: bufbuild/buf-setup-action@v1

      - name: Generate Swagger JSON
        run: |
          buf generate --template buf.gen.doc.yaml

      - name: Install swagger-cli
        run: npm install -g swagger-cli@3.0.0

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: docs/index.html
          github_token: ${{ secrets.GITHUB_TOKEN }}


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
